name: Sync File from Upstream Repo

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 1 * * *' # Mỗi ngày lúc 1:00 UTC
  workflow_dispatch: # Cho phép chạy tay

jobs:
  sync-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Download upstream file
        run:
          curl -o Ads.lsr https://raw.githubusercontent.com/bigdargon/hostsVN/master/option/hostsVN-surge-rule.conf
      - name: Commit & push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Ads.lsr 
          git diff --cached --quiet || git commit -m "🔄 Sync from source-repo"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
